name: cenv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py313h06a4308_0
  - aiohttp=3.11.10=py313h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h865e1df_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py313h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py313hdb19cb5_0
  - cuda-version=12.9=h4f385c5_3
  - datasets=3.3.2=py313h06a4308_0
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.3.8=py313h06a4308_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - filelock=3.17.0=py313h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py313h5eee18b_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - huggingface_hub=0.29.2=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libgrpc=1.71.0=h2d74bed_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxgboost=3.0.0=cuda128_hacb7753_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.0=py313h68cf311_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - multidict=6.1.0=py313h5eee18b_0
  - multiprocess=0.70.15=py313h06a4308_0
  - nccl=2.26.5.1=ha44e49d_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.10.1=py313h3c60e43_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.0=h7b32b05_1
  - orc=2.1.1=hd396ef6_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313hac6e08b_1
  - pip=25.0=py313h06a4308_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py313h5eee18b_0
  - psutil=7.0.0=py313h536fd9c_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.0.0=cuda128_pyh3ef1b53_1
  - pyarrow=19.0.0=py313h6a678d5_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h5eee18b_0
  - python_abi=3.13=0_cp313
  - pytz=2024.1=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - pyzmq=26.2.0=py313h8e95178_1
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py313h5eee18b_0
  - requests=2.32.3=py313h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py313h8a85203_0
  - scikit-learn=1.6.1=py313h8ef605b_0
  - scipy=1.15.2=py313h86fcf2b_0
  - seaborn=0.13.2=py313h06a4308_2
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py313hb8e4a85_0
  - tornado=6.5=py313h536fd9c_0
  - tqdm=4.67.1=py313h7040dfc_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.49.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py313h06a4308_0
  - xgboost=3.0.0=cuda128_pyh68bd8d9_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py313h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - cycler==0.12.1
      - dm-tree==0.1.8
      - einops==0.8.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.14.0
      - huggingface-hub==0.29.3
      - idna==3.10
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - keras==3.11.3
      - libclang==18.1.1
      - lightning-utilities==0.14.0
      - llvmlite==0.44.0
      - markdown==3.7
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.13.0.50
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.28.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.4.127
      - opt-einsum==3.4.0
      - optree==0.17.0
      - pluggy==1.6.0
      - protobuf==6.30.0
      - pyparsing==3.2.1
      - pytest==9.0.2
      - rich==14.1.0
      - shap==0.47.2
      - slicer==0.0.8
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-model-optimization==0.8.0
      - termcolor==3.1.0
      - threadpoolctl==3.5.0
      - timm==1.0.15
      - torch==2.6.0
      - torchmetrics==1.6.2
      - torchvision==0.21.0
      - triton==3.2.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
prefix: /home/misra8/anaconda3/envs/cenv
